version: "3.3"

services:
  opservatory-worker:
    build: .
    ports:
     - "80:5000"
    volumes:
      - ./volumes:/app/opservatory/volumes
      - ./volumes/inventory:/app/opservatory/infrastructure/inventory
    logging:
      options:
        max-size: 50m
